apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-service
data:
  SCALITY_ACCESS_KEY_ID: RkO3HsIqsTgoy1bSFD3O
  SCALITY_SECRET_ACCESS_KEY: 62BYF7VJMSSMV5Je3aDh
  S3BACKEND: file

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: s3-service
  name: s3-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-service
  template:
    metadata:
      labels:
        app: s3-service
    spec:
      containers:
      - name: s3-service
        image: scality/s3server:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: s3-service
        volumeMounts:
        - mountPath: /usr/src/app/localData
          name: s3data
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 750Mi
      volumes:
        - name: s3data
          hostPath:
            path: /opt/s3_scality/app/localData
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: s3-service
  name: s3-service
spec:
  type: NodePort
  selector:
    app: s3-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    nodePort: 30455

